# Generated by Django 5.2.2 on 2025-06-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Image Category')),
            ],
            options={
                'verbose_name': 'Image Category',
                'verbose_name_plural': 'Image Categories',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Image Title')),
                ('imageUrl', models.ImageField(upload_to='', verbose_name='image url')),
            ],
        ),
        migrations.CreateModel(
            name='ICPeering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.ImageField(upload_to='', verbose_name='image url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ic_peering', to='images.imagecategory', verbose_name='Image Category')),
            ],
            options={
                'verbose_name': 'IC Peering',
                'verbose_name_plural': 'IC Peerings',
            },
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='images',
            field=models.ManyToManyField(related_name='categories', to='images.images', verbose_name='Images'),
        ),
    ]
