# Generated by Django 5.2.2 on 2025-06-09 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagecategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image Category', 'verbose_name_plural': 'Image Categories'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-created_at'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.RemoveField(
            model_name='imagecategory',
            name='images',
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagecategory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.imagecategory'),
        ),
        migrations.AddField(
            model_name='images',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='images',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='images',
            name='imageUrl',
            field=models.ImageField(upload_to='images/', verbose_name='Image URL'),
        ),
        migrations.DeleteModel(
            name='ICPeering',
        ),
    ]
