# Generated by Django 5.2.2 on 2025-06-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagecategory_options_alter_images_options_and_more'),
    ]

    operations = [
    ]
