# Generated by Django 5.2.2 on 2025-06-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jsons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='JSON Title')),
                ('json_data', models.JSONField(verbose_name='JSON Data')),
            ],
        ),
        migrations.CreateModel(
            name='JsonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='JSON Category')),
                ('jsons', models.ManyToManyField(related_name='categories', to='jsons.jsons', verbose_name='JSONs')),
            ],
            options={
                'verbose_name': 'JSON Category',
                'verbose_name_plural': 'JSON Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='JCPeering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jc_peering_category', to='jsons.jsoncategory', verbose_name='JSON Category')),
                ('json_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jc_peering', to='jsons.jsons', verbose_name='JSON Data')),
            ],
            options={
                'verbose_name': 'JC Peering',
                'verbose_name_plural': 'JC Peerings',
                'ordering': ['json_data__title'],
            },
        ),
    ]
