# Generated by Django 5.2.2 on 2025-06-09 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jsoncategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'JSON Category', 'verbose_name_plural': 'JSON Categories'},
        ),
        migrations.AlterModelOptions(
            name='jsons',
            options={'ordering': ['-created_at'], 'verbose_name': 'JSON', 'verbose_name_plural': 'JSONs'},
        ),
        migrations.RemoveField(
            model_name='jsoncategory',
            name='jsons',
        ),
        migrations.AddField(
            model_name='jsoncategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jsoncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsoncategory',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jsons',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jsons', to='jsons.jsoncategory'),
        ),
        migrations.AddField(
            model_name='jsons',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jsons',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='JCPeering',
        ),
    ]
