# Generated by Django 5.2.2 on 2025-06-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0002_alter_jsoncategory_options_alter_jsons_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsons',
            old_name='json_data',
            new_name='jsonData',
        ),
        migrations.RemoveField(
            model_name='jsoncategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jsoncategory',
            name='title',
        ),
        migrations.AddField(
            model_name='jsoncategory',
            name='category_name',
            field=models.CharField(default='default category', max_length=100),
        ),
        migrations.AlterField(
            model_name='jsons',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
