# Generated by Django 5.2.2 on 2025-06-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0003_rename_json_data_jsons_jsondata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
