# Generated by Django 5.2.2 on 2025-06-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0004_alter_jsoncategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
