# Generated by Django 5.2.2 on 2025-06-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0005_alter_jsoncategory_id'),
    ]

    operations = [
    ]
