# Generated by Django 5.2.2 on 2025-07-16 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsons', '0006_auto_20250609_0123'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jsons',
            name='flagged_reason',
            field=models.TextField(blank=True, help_text='검열 사유', null=True),
        ),
        migrations.AddField(
            model_name='jsons',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='검열 통과 여부'),
        ),
        migrations.AddField(
            model_name='jsons',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='욕설/금지어 포함 여부'),
        ),
        migrations.AddField(
            model_name='jsons',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_jsons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JsonBannedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JSON Banned Word',
                'verbose_name_plural': 'JSON Banned Words',
                'ordering': ['word'],
            },
        ),
    ]
